// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQJ5ySw9YjpHPstat3Qcs5fFvGj4QjRs',
    appId: '1:133233021863:web:9ed9686e873ec55c42dc82',
    messagingSenderId: '133233021863',
    projectId: 'wddy-df6f1',
    authDomain: 'wddy-df6f1.firebaseapp.com',
    storageBucket: 'wddy-df6f1.firebasestorage.app',
    measurementId: 'G-1V80R9KHC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2RtA6jzyIYjt3CQYlJWRFkmNoRmqxDc8',
    appId: '1:133233021863:android:d9034e4e161a595742dc82',
    messagingSenderId: '133233021863',
    projectId: 'wddy-df6f1',
    storageBucket: 'wddy-df6f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOmhlyI7Cymv8PTT9rYvuwu5Rol6E1xw',
    appId: '1:133233021863:ios:37ed63b828fc432b42dc82',
    messagingSenderId: '133233021863',
    projectId: 'wddy-df6f1',
    storageBucket: 'wddy-df6f1.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOmhlyI7Cymv8PTT9rYvuwu5Rol6E1xw',
    appId: '1:133233021863:ios:37ed63b828fc432b42dc82',
    messagingSenderId: '133233021863',
    projectId: 'wddy-df6f1',
    storageBucket: 'wddy-df6f1.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxQJ5ySw9YjpHPstat3Qcs5fFvGj4QjRs',
    appId: '1:133233021863:web:1dd6fcfaa94d15a742dc82',
    messagingSenderId: '133233021863',
    projectId: 'wddy-df6f1',
    authDomain: 'wddy-df6f1.firebaseapp.com',
    storageBucket: 'wddy-df6f1.firebasestorage.app',
    measurementId: 'G-D66VVQ7T9Y',
  );
}
